# Generated by Django 3.1.2 on 2020-10-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shenasapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='accepted',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='user',
            name='nationalCode',
            field=models.CharField(default='0312044151', max_length=16),
        ),
        migrations.AddField(
            model_name='user',
            name='shenasnameCode',
            field=models.CharField(default='0312044151', max_length=16),
        ),
        migrations.CreateModel(
            name='ShenasnameImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shenasapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PersonallyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shenasapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='NationalCardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_pic', models.ImageField(default='none/no-img.jpg', upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shenasapp.user')),
            ],
        ),
    ]
