# Generated by Django 3.1.2 on 2020-10-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shenasapp', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accepted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationalCode',
            field=models.CharField(default='0312044151', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shenasnameCode',
            field=models.CharField(default='0312044151', max_length=16, null=True),
        ),
    ]
