# Generated by Django 3.1.2 on 2020-10-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shenasapp', '0004_auto_20201004_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='lastName',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='abc', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationalCode',
            field=models.CharField(default='0312044151', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='shenasnameCode',
            field=models.CharField(default='0312044151', max_length=16),
        ),
    ]
